[variables]
NODE_VERSION = "20"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm run start"
